### ISSUE TITLE
网站无法正常使用

### ISSUE THREAD

**Issue by dev-techmoe** [zjcqoo/zjcqoo.github.io#3]
无法打开任何链接

```
TypeError: Cannot read property 'node_map' of undefined
    at r (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:5762)
    at Object.u (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:5865)
    at f (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:115272)
    at I (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:118008)
    at C (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:118984)
    at https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:119324
    at https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/
```

**Comment by dev-techmoe** [comment]
刚刚尝试了一下隐身模式打开网站，发现可以正常使用。但是回到非隐身模式，在尝试F12硬性重新加载，甚至在“更多工具->清除浏览数据”中清除整个浏览器的缓存也没有改善问题。不知道有没有其他解决思路？

**Comment by czpwpq** [comment]
的确存在这个问题，我再尝试是否可以去掉cdn使用

**Comment by czpwpq** [comment]
TypeError: Cannot read property 'node_map' of undefined
    at r (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:5762)
    at Object.u (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:5865)
    at f (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:115272)
    at I (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:118008)
    at C (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:118984)
    at https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:119324
    at https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.4386e2f9.js:1:119352

**Comment by czpwpq** [comment]
测试时有时候会发生这个问题，包括官方的demo有时候也会

**Comment by baobaoblue** [comment]
从昨天晚上貌似就用不了了，报这个错
TypeError: Cannot read property 'has' of undefined
    at f (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.176d9e8e.js:1:114074)
    at C (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.176d9e8e.js:1:117805)
    at I (https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.176d9e8e.js:1:118781)
    at https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.176d9e8e.js:1:119121
    at https://cdn.jsdelivr.net/gh/zjcqoo/zjcqoo.github.io@master/assets/bundle.176d9e8e.js:1:119149

**Comment by czpwpq** [comment]
请一下缓存会好，但是过段时间就不行了。等修复把

**Comment by lishihong** [comment]
用不了呀
